### ISSUE TITLE
Reporting of n_mismatch and n_indel is lower than in the image for PacBio

### ISSUE THREAD

**Issue by jzook** [nspies/svviz2#42]
At least for PacBio, there often seem to be more variants visible in the flanking regions than are reported in n_mismatch and n_indel.  I'm also not sure what N_total means, but it is very frequently exactly 100, though not always.  I've attached a couple examples, and here is the command I ran, though you might want to just grep these 2 IDs from the vcf since otherwise it'll run 100 sites:

`genosv --also-plot-context 4000 --outdir /scratch/PI/msalit/jzook/AJTrio/svvizconfirm/union_170509/genosv20a1PBv030bPASSbionanodiffgt300 --ref /scratch/PI/msalit/jzook/references/human_g1k_v37.fasta -V /scratch/PI/msalit/jzook/AJTrio/svvizconfirm/union_170509/union_170509_refalt.2.2.2.clustered.simpleINFO.techcounts.bionanodiffgt300.vcf.gz /scratch/PI/msalit/jzook/AJTrio/PBNGMLR/HG002_PB_70x.bam,sequencer=pacbio /scratch/PI/msalit/jzook/AJTrio/PBNGMLR/HG003_PB_30x.bam,sequencer=pacbio /scratch/PI/msalit/jzook/AJTrio/PBNGMLR/HG004_PB_30x.bam,sequencer=pacbio
`

[HG2_PB_SVrefinePBcRDovetail_7719.del_X_91678133.pdf](https://github.com/nspies/genosv/files/1285009/HG2_PB_SVrefinePBcRDovetail_7719.del_X_91678133.pdf)

[HG2_PB_SVrefinePBcRDovetail_7571.SequenceDefinedVariant.22_50933765-50933765.pdf](https://github.com/nspies/genosv/files/1285029/HG2_PB_SVrefinePBcRDovetail_7571.SequenceDefinedVariant.22_50933765-50933765.pdf)

**Comment by nspies** [comment]
I've adjusted upward the distance at which we're looking for variants. It should now be up to 1kb upstream and downstream of the breakpoints, which should give it a bit more space to make this identification. Note that for short-read data there may not be this much space upstream and downstream of the event, so the `n_total` will be less than 1000.
