### ISSUE TITLE
Add number of inserted bases to visualization

### ISSUE THREAD

**Issue by jzook** [nspies/svviz2#45]
It would be great to add the number of inserted bases (and maybe the number of deleted bases as well) inside the insertions or deletion similar to how IGV does now, at least for indels larger than a certain size (maybe ~5bp?).  An example for IGV is in Fig 2b and 2c here:
http://www.pacb.com/blog/igv-3-improves-support-pacbio-long-reads/

**Comment by nspies** [comment]
closed by nspies/genomeview@d2bfe3ea8bbaab395923409c7948f623139c9f67
