### ISSUE TITLE
Labeling large insertions

### ISSUE THREAD

**Issue by jzook** [nspies/svviz2#54]
It would be helpful to distinguish large insertions from small insertions in both the visualization and the annotations output since right now it is hard to tell if there is a large insertion

**Comment by nspies** [comment]
Can you explain a little more what's hard to see and how to improve it? An example or two might be helpful.

**Comment by jzook** [comment]
Sure I will find some examples as I do more curations and send them to you.
Something like what igv does putting the number of inserted bases inside
the I bar would be ideal

**Comment by nspies** [comment]
Ah, I see. You're referring to indels other than the variant of interest? I think this already happens, but only if you're zoomed in enough. I could make it more aggressive about labeling variants if they're over a certain size, even when you're zoomed out. What do you think is reasonable?

Right now, anything under 5bp is ignored, and it tries to draw a label if it's 10bp or larger, but only draws it if it's zoomed to a level where the text would fit within the indel. I can drop that latter part.

**Comment by nspies** [comment]
you can try installing a fix from a genomeview branch: `pip install -U git+https://github.com/nspies/genomeview.git@indel_labels`. Let me know if that's what you're looking for.

**Comment by jzook** [comment]
After updating to the latest svviz2 and then the label_indels genomeview
branch, I get the error below that seems to relate to the insertion
labeling:

(svviz20a2) [*jzook*@sh-18-28 ~]$ svviz2 --min-mapq 20 --downsample 1000
--outdir
/scratch/PI/msalit/jzook/AJTrio/SVv050/genosv20a110xsplithapHP10XtrioRTGv0502techor4callsetMQ20
--ref /oak/stanford/groups/msalit/shared/genomes/hg19/hg19.fasta -V
/scratch/PI/msalit/jzook/AJTrio/SVv050/union_171212_refalt.2.2.2.clustered.simpleINFO.techcounts.2techor4callset_200.vcf.gz
/oak/stanford/groups/msalit/shared/giab/hg19/HG002/HG002_10x_84x_RG_HP10xtrioRTG.bam,split_hap=true

ssw library not found

rpy2 could not be imported; dotplots will not be generated

2018-06-19 07:20:57 - svviz2.app.sample         - INFO  - Loaded
pre-computed read statistics for HG002_10x_84x_RG_HP10xtrioRTG_hap1

2018-06-19 07:20:57 - svviz2.app.sample         - INFO  - Loaded
pre-computed read statistics for HG002_10x_84x_RG_HP10xtrioRTG_hap2

2018-06-19 07:20:57 - svviz2.app.sample         - INFO  - Loaded
pre-computed read statistics for HG002_10x_84x_RG_HP10xtrioRTG_hap-unknown

2018-06-19 07:20:57 - svviz2.app.main           - INFO  - Search distance:
647bp

2018-06-19 07:20:57 - svviz2.app.main           - INFO  - Search distance:
647bp

2018-06-19 07:20:57 - svviz2.app.main           - INFO  - Search distance:
647bp

2018-06-19 07:20:57 - svviz2.app.main           - INFO  - Align distance:
880bp

[W::vcf_parse] FILTER 'NOT2TECH' is not defined in the header

[W::vcf_parse] INFO 'ClusterIDs' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'NumClusterSVs' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'ExactMatchIDs' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'NumExactMatchSVs' is not defined in the header,
assuming Type=String

[W::vcf_parse] INFO 'ClusterMaxShiftDist' is not defined in the header,
assuming Type=String

[W::vcf_parse] INFO 'ClusterMaxSizeDiff' is not defined in the header,
assuming Type=String

[W::vcf_parse] INFO 'ClusterMaxEditDist' is not defined in the header,
assuming Type=String

[W::vcf_parse] INFO 'PBcalls' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'Illcalls' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'TenXcalls' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'CGcalls' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'PBexactcalls' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'Illexactcalls' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'TenXexactcalls' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'CGexactcalls' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'HG2count' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'HG3count' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'HG4count' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'NumTechs' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'NumTechsExact' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'DistBack' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'DistForward' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'DistMin' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'DistMinlt1000' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'MultiTech' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'MultiTechExact' is not defined in the header, assuming
Type=String

[W::vcf_parse] INFO 'sizecat' is not defined in the header, assuming
Type=String

2018-06-19 07:20:57 - svviz2.app.datahub        - INFO  - Working on
variant 0: Deletion::14:80,884,184-80,884,208(25)

2018-06-19 07:20:57 - svviz2.app.datahub        - INFO  - Looking for
existing realignments; will try to open a few bam files that may not yet
exist...

[E::hts_open_format] Failed to open file
/scratch/PI/msalit/jzook/AJTrio/SVv050/genosv20a110xsplithapHP10XtrioRTGv0502techor4callsetMQ20/svviz2-temp7cizaqsh/HG3_Ill_150bpfermikitraw_18808.del_14_80884184.HG002_10x_84x_RG_HP10xtrioRTG_hap1.alt.sorted.bam

[E::hts_open_format] Failed to open file
/scratch/PI/msalit/jzook/AJTrio/SVv050/genosv20a110xsplithapHP10XtrioRTGv0502techor4callsetMQ20/svviz2-temp7cizaqsh/HG3_Ill_150bpfermikitraw_18808.del_14_80884184.HG002_10x_84x_RG_HP10xtrioRTG_hap2.alt.sorted.bam

[E::hts_open_format] Failed to open file
/scratch/PI/msalit/jzook/AJTrio/SVv050/genosv20a110xsplithapHP10XtrioRTGv0502techor4callsetMQ20/svviz2-temp7cizaqsh/HG3_Ill_150bpfermikitraw_18808.del_14_80884184.HG002_10x_84x_RG_HP10xtrioRTG_hap-unknown.alt.sorted.bam

2018-06-19 07:20:57 - svviz2.app.datahub        - INFO  - Analyzing sample
HG002_10x_84x_RG_HP10xtrioRTG_hap1

2018-06-19 07:20:57 - svviz2.io.getreads        - INFO  - Loading more read
pairs...

2018-06-19 07:20:59 - svviz2.io.getreads        - INFO  - TIME to read
batch: 1.9s

Reads with only N: 0

2018-06-19 07:20:59 - svviz2.app.datahub        - INFO  - Analyzing 165
read pairs

2018-06-19 07:20:59 - svviz2.app.genomesource   - INFO  - Loading bwa index
from file /oak/stanford/groups/msalit/shared/genomes/hg19/hg19.fasta...

[M::bwa_idx_load_from_disk] read 0 ALT contigs

2018-06-19 07:21:03 - svviz2.app.genomesource   - INFO  - Loading bwa index
done.

100%|████████████████████████████████████████| 165/165 [00:00<00:00,
186.61it/s]

REF: 8.325 ALT: 4.0

2018-06-19 07:21:04 - svviz2.app.datahub        - INFO  - Analyzing sample
HG002_10x_84x_RG_HP10xtrioRTG_hap2

2018-06-19 07:21:04 - svviz2.io.getreads        - INFO  - Loading more read
pairs...

2018-06-19 07:21:06 - svviz2.io.getreads        - INFO  - TIME to read
batch: 1.7s

Reads with only N: 0

2018-06-19 07:21:06 - svviz2.app.datahub        - INFO  - Analyzing 180
read pairs

100%|████████████████████████████████████████| 180/180 [00:00<00:00,
200.32it/s]

REF: 1.3 ALT: 14.325

2018-06-19 07:21:07 - svviz2.app.datahub        - INFO  - Analyzing sample
HG002_10x_84x_RG_HP10xtrioRTG_hap-unknown

2018-06-19 07:21:07 - svviz2.io.getreads        - INFO  - Loading more read
pairs...

2018-06-19 07:21:09 - svviz2.io.getreads        - INFO  - TIME to read
batch: 1.7s

Reads with only N: 0

2018-06-19 07:21:09 - svviz2.app.datahub        - INFO  - Analyzing 64 read
pairs

100%|██████████████████████████████████████████| 64/64 [00:00<00:00,
199.19it/s]

REF: 0.4 ALT: 3.225

TIME::: 12.352047443389893

2018-06-19 07:21:10 - root                      - INFO  - Trying to locate
auxiliary svg converter...

/bin/sh: rsvg-convert: command not found

/bin/sh: inkscape: command not found

2018-06-19 07:21:10 - root                      - WARNING - No converters
found to 'pdf'; output visualizations will be in svg format

2018-06-19 07:21:10 - root                      - WARNING - (To convert to
pdf/png, install rsvg-convert, inkscape or webkitToPDF and place the binary
in $PATH)

/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/bamtrack.py:153:
RuntimeWarning: invalid value encountered in true_divide

  if not self.mismatch_counts or alt=="N" or
self.mismatch_counts.query(alt, genome_position+i):

Traceback (most recent call last):

  File "/home/users/jzook/svviz20a2/bin/svviz2", line 11, in <module>

    load_entry_point('svviz2==2.0a3', 'console_scripts', 'svviz2')()

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/svviz2/app/main.py",
line 60, in main

    run(datahub)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/svviz2/app/main.py",
line 46, in run

    visualize.visualize(datahub)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/svviz2/visualize/visualize.py",
line 58, in visualize

    _visualize(datahub)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/svviz2/visualize/visualize.py",
line 103, in _visualize

    export.export(doc, datahub, context)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/svviz2/io/export.py",
line 36, in export

    for l in sv_document.render():

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/genomeview.py",
line 47, in render

    yield from renderer.render(element)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/svg.py",
line 196, in render

    for subelement in element.render(self):

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/genomeview.py",
line 98, in render

    yield from subrenderer.render(view)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/svg.py",
line 196, in render

    for subelement in element.render(self):

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/genomeview.py",
line 137, in render

    yield from subrenderer.render(track)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/svg.py",
line 196, in render

    for subelement in element.render(self):

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/svviz2/visualize/visualize.py",
line 177, in render

    yield from super().render(renderer)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/bamtrack.py",
line 383, in render

    yield from self.draw_read_pair(renderer, cur_reads)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/bamtrack.py",
line 361, in draw_read_pair

    yield from self.draw_interval(renderer, interval)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/bamtrack.py",
line 135, in draw_interval

    yield from self._draw_cigar(renderer, interval)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/bamtrack.py",
line 266, in _draw_cigar

    yield from self._draw_insertion(renderer, length, genome_position,
yoffset)

  File
"/home/users/jzook/svviz20a2/lib/python3.6/site-packages/genomeview/bamtrack.py",
line 202, in _draw_insertion

    width = label_width

UnboundLocalError: local variable 'label_width' referenced before assignment

(svviz20a2) [*jzook*@sh-18-28 ~]$

**Comment by nspies** [comment]
Sorry about that, can you try again?

**Comment by jzook** [comment]
This works now and I think the insertion visualization is a nice
improvement, so I'd say go ahead and push it to the main release - thanks!
