### ISSUE TITLE
Installation failing for zlib.h not found

### ISSUE THREAD

**Issue by MaestSi** [nspies/svviz2#58]
Dear svviz2 developer,
I am trying to install svviz2 software in a miniconda virtual environment.
I created the virtual env svviz2_env with python3.7, and installed gcc, trf and rpy2.
Then, after activating the environment, I typed:
`pip3 install -U git+git://github.com/nspies/svviz2.git`
This command gives some errors that seem to be due to the compiler not being able to find zlib, which I have already installed within the conda virtual env.
In particular, some lines of the error message that seem relevant to me are:

> /mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/pysam -I/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/pysam/include/htslib -I/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/pysam/include/samtools -I/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/numpy/core/include -I/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/include/python3.7m -c src/svviz2/remap/_mapq.c -o build/temp.linux-x86_64-3.7/src/svviz2/remap/_mapq.o
>   In file included from /mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/pysam/include/htslib/htslib/hts.h:35:0,
>                    from /mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/pysam/include/htslib/htslib/sam.h:31,
>                    from /mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/pysam/htslib_util.h:4,
>                    from src/svviz2/remap/_mapq.c:618:
>   /mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/pysam/include/htslib/htslib/hts_log.h:52:6: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>    enum htsLogLevel hts_get_log_level();
>         ^~~~~~~~~~~
>   In file included from src/svviz2/remap/_mapq.c:620:0:
>   /mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/pysam/include/htslib/htslib/bgzf.h:35:10: fatal error: zlib.h: No such file or directory
>    #include <zlib.h>
>             ^~~~~~~~
>   compilation terminated.
>   error: command '/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
> 
>   ----------------------------------------
>   Failed building wheel for svviz2

> checking zlib.h usability... no
>   checking zlib.h presence... no
>   checking for zlib.h... no
>   checking for library containing gzopen... no
>   configure: error: libz not found, please install zlib (http://www.zlib.net/)
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-install-t3fdmtjx/seqlib/setup.py", line 224, in <module>
>       zip_safe=False,
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
>       return distutils.core.setup(**attrs)
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/dist.py", line 966, in run_commands
>       self.run_command(cmd)
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 188, in run
>       self.run_command('build')
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/command/build.py", line 135, in run
>       self.run_command(cmd_name)
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
>       _build_ext.run(self)
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/command/build_ext.py", line 339, in run
>       self.build_extensions()
>     File "/tmp/pip-install-t3fdmtjx/seqlib/setup.py", line 152, in build_extensions
>       build_ext.build_extensions(self)
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
>       self._build_extensions_serial()
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
>       self.build_extension(ext)
>     File "/tmp/pip-install-t3fdmtjx/seqlib/setup.py", line 157, in build_extension
>       compile_seqlib()
>     File "/tmp/pip-install-t3fdmtjx/seqlib/setup.py", line 73, in compile_seqlib
>       check_call("./configure CFLAGS=-fPIC CXXFLAGS=-fPIC")
>     File "/tmp/pip-install-t3fdmtjx/seqlib/setup.py", line 26, in check_call
>       subprocess.check_call(command, shell=True)
>     File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.7/subprocess.py", line 347, in check_call
>       raise CalledProcessError(retcode, cmd)
>   subprocess.CalledProcessError: Command './configure CFLAGS=-fPIC CXXFLAGS=-fPIC' returned non-zero exit status

Similar errors are printed out informing that also seqlib and genomeview build failed.

Usually, I would try to fix this telling gcc the path to zlib/include with -I flag. However, in this case I don't know how to fix it, since I don't have a config or a Makefile.
Thanks in advance.

**Comment by nspies** [comment]
Does [this stackoverflow answer](https://stackoverflow.com/questions/18783390/python-pip-specify-a-library-directory-and-an-include-directory) provide a solution?

**Comment by MaestSi** [comment]
Dear nspies,
I realized that possibly the problem was given by the fact that conda installing rpy2 package in the virtual environment svviz2_env caused the installation of R (which comes with gcc compiler) within the package. I therefore tried to install rpy2 package outside of the virtual environment, and repeat the svviz2 installation using my own gcc compiler.
I think I am almost there, since svviz2 seems to be installed, however when typing `svviz2 -h` it gives error:

> ssw library not found
> rpy2 could not be imported; dotplots will not be generated
> ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview:
>   pip install --upgrade --force-reinstall genomeview
> Traceback (most recent call last):
>   File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/bin/svviz2", line 6, in <module>
>     from svviz2.app.main import main
>   File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.6/site-packages/svviz2/app/main.py", line 7, in <module>
>     from svviz2.visualize import visualize
>   File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.6/site-packages/svviz2/visualize/visualize.py", line 8, in <module>
>     from genomeview import Document, ViewRow, GenomeView
>   File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.6/site-packages/genomeview/__init__.py", line 24, in <module>
>     from genomeview.bamtrack import *
>   File "/mnt/cifs01/simone/software/miniconda2/envs/svviz2_env/lib/python3.6/site-packages/genomeview/bamtrack.py", line 6, in <module>
>     from genomeview import MismatchCounts
> ImportError: cannot import name 'MismatchCounts'
> 

I tried to force reinstall both genomeview and svviz2, but I still get these errors.

**Comment by MaestSi** [comment]
Dear nspies,
I have solved it! I think the error was due to cython package missing in my virtual environment. Maybe it should be cited as a prerequisite for running svviz2!
Thanks
