### ISSUE TITLE
git hangs when installing via the default install instruction

### ISSUE THREAD

**Issue by pwaltman** [nspies/svviz2#67]
I'm not sure what the issue is, but the default install instruction on the Readme no longer works, and git command just hangs at that point.

I can clone it, but the code with the pip3 install command (with the git repo embedded) just hangs.

I'm running on WSL, using Ubuntu 22.10.

Note, I am able to clone the repo using the following command:
`git clone --filter=blob:none --quiet https://github.com/nspies/svviz2.git` (replacing the 'git://....` url with `https://`

**Comment by nspies** [comment]
hi @pwaltman - can you try this command instead to install svviz2?

`pip install -U git+https://github.com/nspies/svviz2.git@cython_less_than3 -v`

If that works, I can merge those changes to the main branch

**Comment by pwaltman** [comment]
it definitely started the process, but failed when I got to installing `seqlib`:  I realize that isn't your library, but it looks like it hasn't been updated since August, 2017.

`  cwd: /var/tmp/pip-install-4m9hirog/seqlib_04b5eb25c55242619555d089c4ec2204/
  Building wheel for seqlib (setup.py) ... error
  ERROR: Failed building wheel for seqlib
  Running setup.py clean for seqlib
  Running command python setup.py clean
  running clean
  removing 'build/lib.linux-x86_64-cpython-310' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.10' does not exist -- can't clean it
  removing 'build'
Failed to build svviz2 seqlib
ERROR: Could not build wheels for svviz2, seqlib, which is required to install pyproject.toml-based projects`

**Comment by pwaltman** [comment]
this is the error I get when I try to manually install the seqlib library:
`      gcc -g -Wall -Wno-unused-function -O2 -fPIC -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS bwashm.o bwase.o bwaseqio.o bwtgap.o bwtaln.o bamlite.o bwape.o kopen.o pemerge.o maxk.o bwtsw2_core.o bwtsw2_main.o bwtsw2_aux.o bwt_lite.o bwtsw2_chain.o fastmap.o bwtsw2_pair.o main.o -o bwa -L. -lbwa -lm -lz -lpthread -lrt
      /usr/bin/ld: ./libbwa.a(rope.o):/var/tmp/pip-install-iylh_v5m/seqlib_f8131b53cbc44b30bb7f1583c1edd438/lib/SeqLib/bwa/rle.h:33: multiple definition of `rle_auxtab'; ./libbwa.a(bwtindex.o):/var/tmp/pip-install-iylh_v5m/seqlib_f8131b53cbc44b30bb7f1583c1edd438/lib/SeqLib/bwa/rle.h:33: first defined here
      /usr/bin/ld: ./libbwa.a(rle.o):/var/tmp/pip-install-iylh_v5m/seqlib_f8131b53cbc44b30bb7f1583c1edd438/lib/SeqLib/bwa/rle.h:33: multiple definition of `rle_auxtab'; ./libbwa.a(bwtindex.o):/var/tmp/pip-install-iylh_v5m/seqlib_f8131b53cbc44b30bb7f1583c1edd438/lib/SeqLib/bwa/rle.h:33: first defined here
      collect2: error: ld returned 1 exit status
      make[2]: *** [Makefile:31: bwa] Error 1
      make[2]: Leaving directory '/var/tmp/pip-install-iylh_v5m/seqlib_f8131b53cbc44b30bb7f1583c1edd438/lib/SeqLib/bwa'`

**Comment by nspies** [comment]
I'm not sure I can provide much more help here - the above command is installing fine for me into a fresh virtualenv running python 3.9.13 in amazon linux 2 (centos/redhat flavor). After installing svviz2, I can import seqlib without issue.

**Comment by pwaltman** [comment]
okay. I'm using a conda environment with python 3.10. I wonder if that might be the issue. What version of centos are you using? Also, I'll edit the dockerfile that I copied from here (which uses ubuntu 18.04 as the base image: 
https://biodockerfiles.github.io/svviz2-2-0a3/

If that builds, then that should resolve the issue (as I plan on using this via docker)

**Comment by pwaltman** [comment]
is there a github repo for the seqlib project? I didn't realize that you are the maintainer for that python library, but I don't see a corresponding repo associated with your github account.

**Comment by pwaltman** [comment]
The install works in the Dockerfile that I linked to in a previous comment, although I needed to add a few ubuntu repos to get it to work.

The seqlib install issue seems to be resolved, which indicates to me that there's a versioning issue with seqlib that will need to be addressed at some point as the base image (Ubuntu 18.04) is 5+ years old at this point.

**Comment by pwaltman** [comment]
FYI, I looked up the compiler error that I'm getting and it's a bwa issue that needs to be resolved, but which hasn't been address in 2+ years, evidently, sigh:

https://www.biostars.org/p/9521965/#9522000

And this is the issue on github: https://github.com/lh3/bwa/issues/314

Evidently, the fix is a one-word fix to a single file (adding the extern key word to the variable declaration for `rle_auxtab` on line 33 of `rle.h`

People have been either working around it by modifying it themselves, or changing the compile arguments to use `-fcommon`

But it's pretty clear that the maintainer isn't going to fix bwa (he's ignored all requests to fix the issue).  Anyway, the workaround is to use an older for the base system, but I wanted to pass along the info.

**Comment by nspies** [comment]
Thanks for the updates. Happy to accept pull requests if there are things to be done from this side.
